import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'
import Navbar from '../components/Navbar/'
import Hero from '../components/HeroSection'
import WhoWeAre from '../components/About/WhoWeAre'
import OurBigPicture from '../components/About/OurBigPicture'
const Section = styled.section`
width:100vw;
padding:0;

`
const Home: NextPage = () => {
  return (
    <Section className={styles.container}>
      <Head>
        <title>NXT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <WhoWeAre />
      <OurBigPicture />
    </Section>
  )
}

export default Home
